name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: typst-community/setup-typst@v3
      - name: Install fonts
        run: |
          sudo apt update
          sudo apt install fonts-noto
          fc-cache -vf
      - run: typst fonts
      - run: typst compile sample.typ sample.pdf
      - name: Create page directory
        run: |
          mkdir _pages
          mv ./sample.pdf ./_pages/sample.pdf
          echo "<meta http-equiv=\"refresh\" content=\"0;URL='$(gh api "repos/$GITHUB_REPOSITORY" --jq '.html_url')'\">" > ./_pages/index.html
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _pages/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
